updated template and readme

diff --git a/create_ami.yaml b/create_ami.yaml
--- a/create_ami.yaml
+++ b/create_ami.yaml
@@ -1,7 +1,10 @@
-Description: Create an AMI from an EC2 Spot instance
+Description: NVIDIA Docker AMI
 Parameters:
   InstanceType:
     Description: Instance type to launch EC2 Spot instance
+    Type: String
+  ImageName:
+    Description: AMI name
     Type: String
   KeyName:
     Description: Key name to get an access o the instance
@@ -24,8 +27,7 @@ Resources:
       Role: !GetAtt FindBaseAMILambdaExecutionRole.Arn
       Code:
         ZipFile: !Sub |
-          var aws=require("aws-sdk");var response=require('cfn-response');exports.handler=function(event,context){console.log("request received:\n"+JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{}
-          console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
+          var aws=require("aws-sdk");var response=require('cfn-response');exports.handler=function(event,context){console.log("request received:\n"+JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{};console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
           function failed(err){console.log('FAILED:\n',err);return response.send(event,context,response.FAILED,err,physicalId)}
           if(event.RequestType=='Delete'){console.log('Delete request is ignored');return success()}
           var ec2=new aws.EC2({region:event.ResourceProperties.Region});ec2.describeImages({Filters:[{Name:"name",Values:['ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64*']}],Owners:['099720109477']}).promise().then((data)=>{console.log('Number of found images: ',data.Images.length);var images=data.Images;images.sort(function(x,y){return y.Name.localeCompare(x.Name)});var amiId=!1;for(var j=0;j<images.length;j++){if(isBeta(images[j].Name))continue;amiId=images[j].ImageId;break}
@@ -34,12 +36,6 @@ Resources:
           physicalId=amiId;success()}).catch((err)=>failed(err))};function isBeta(imageName){return imageName.toLowerCase().indexOf("beta")>-1||imageName.toLowerCase().indexOf(".rc")>-1}
       Runtime: nodejs4.3
       Timeout: 30
-  FindBaseAMIFunctionLogGroup:
-    Type: AWS::Logs::LogGroup
-    DependsOn: FindBaseAMIFunction
-    Properties:
-      RetentionInDays: 7
-      LogGroupName: !Join ['', ['/aws/lambda/', !Ref FindBaseAMIFunction]]
   FindBaseAMILambdaExecutionRole:
     Type: AWS::IAM::Role
     Properties:
@@ -69,58 +65,66 @@ Resources:
             - 'ec2:DescribeImages'
             Resource: '*'
 
-  SpotFleet:
-    Type: AWS::EC2::SpotFleet
+  SpotInstance:
+    Type: AWS::EC2::Instance
     Properties:
-      SpotFleetRequestConfigData:
-        IamFleetRole: !GetAtt IAMFleetRole.Arn
-        Type: request
-        TargetCapacity: 1
-        LaunchSpecifications:
-        - InstanceType: !Ref InstanceType
-          ImageId: !Ref FindBaseAMI
-          KeyName: !Ref KeyName
-          EbsOptimized: 'false'
-          BlockDeviceMappings:
-          - DeviceName: /dev/sda1
-            Ebs:
-              DeleteOnTermination: true
-              VolumeType: gp2
-              VolumeSize: 10
-          IamInstanceProfile:
-            Arn: !GetAtt LogRoleInstanceProfile.Arn
-          UserData:
-            'Fn::Base64': !Sub |
-              #!/bin/bash -x
+      LaunchTemplate:
+        LaunchTemplateId: !Ref SpotInstanceLaunchTemplate
+        Version: !GetAtt SpotInstanceLaunchTemplate.LatestVersionNumber
 
-              # install CloudFormation tools
-              apt-get update
-              apt-get -y install python-setuptools
-              mkdir aws-cfn-bootstrap-latest
-              curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
-              easy_install aws-cfn-bootstrap-latest
+  SpotInstanceLaunchTemplate:
+    Type: AWS::EC2::LaunchTemplate
+    Properties:
+      LaunchTemplateData:
+        InstanceType: !Ref InstanceType
+        ImageId: !Ref FindBaseAMI
+        KeyName: !Ref KeyName
+        EbsOptimized: 'false'
+        IamInstanceProfile:
+          Arn: !GetAtt InstanceProfile.Arn
+        InstanceInitiatedShutdownBehavior: terminate
+        InstanceMarketOptions:
+          MarketType: spot
+          SpotOptions:
+            SpotInstanceType: one-time
+            InstanceInterruptionBehavior: terminate
+        BlockDeviceMappings:
+        - DeviceName: /dev/sda1
+          Ebs:
+            VolumeType: gp2
+            DeleteOnTermination: true
+        UserData:
+          'Fn::Base64': !Sub |
+            #!/bin/bash -x
 
-              # install CloudWatch agent
-              /usr/local/bin/cfn-init \
-                --stack ${AWS::StackName} \
-                --resource SpotFleet \
-                --region ${AWS::Region} \
-                -c cwlogs
+            # install CloudFormation tools
+            apt-get update
+            apt-get -y install python-setuptools
+            mkdir aws-cfn-bootstrap-latest
+            curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
+            easy_install aws-cfn-bootstrap-latest
 
-              # install Docker and goofys
-              /usr/local/bin/cfn-init \
-                --stack ${AWS::StackName} \
-                --resource SpotFleet \
-                --region ${AWS::Region} \
-                -c init \
-                -v
+            # install CloudWatch agent
+            /usr/local/bin/cfn-init \
+              --stack ${AWS::StackName} \
+              --resource SpotInstanceLaunchTemplate \
+              --region ${AWS::Region} \
+              -c cwlogs
 
-              # send signal to create an AMI
-              /usr/local/bin/cfn-signal \
-                -e $? \
-                --stack ${AWS::StackName} \
-                --region ${AWS::Region} \
-                --resource InstanceReadyWaitCondition
+            # install Docker and goofys
+            /usr/local/bin/cfn-init \
+              --stack ${AWS::StackName} \
+              --resource SpotInstanceLaunchTemplate \
+              --region ${AWS::Region} \
+              -c init \
+              -v
+
+            # send signal to create an AMI
+            /usr/local/bin/cfn-signal \
+              -e $? \
+              --stack ${AWS::StackName} \
+              --region ${AWS::Region} \
+              --resource InstanceReadyWaitCondition
     Metadata:
       'AWS::CloudFormation::Init':
         configSets:
@@ -162,20 +166,6 @@ Resources:
                 # test nvidia-docker
                 docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
                 docker rmi $(docker images -q)
-
-                # install go
-                curl -O https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz
-                tar -xvf go1.8.linux-amd64.tar.gz
-                mv go /usr/local
-                ln -s /usr/local/go/bin/go /usr/bin/go
-                go version
-
-                # install goofys
-                export GOPATH=$HOME/work
-                go get github.com/kahing/goofys
-                go install github.com/kahing/goofys
-                cp work/bin/goofys /usr/bin/
-                goofys --version
               mode: '000755'
               owner: root
               group: root
@@ -191,13 +181,13 @@ Resources:
 
                 [/var/log/cloud-init-output.log]
                 file = /var/log/cloud-init-output.log
-                log_group_name = ${SpotFleetLogGroup}
+                log_group_name = ${InstanceLogGroup}
                 log_stream_name = {instance_id}/cloud-init-output.log
                 datetime_format = %d/%b/%Y:%H:%M:%S
 
                 [/var/log/cfn-init.log]
                 file = /var/log/cfn-init.log
-                log_group_name = ${SpotFleetLogGroup}
+                log_group_name = ${InstanceLogGroup}
                 log_stream_name = {instance_id}/cfn-init.log
                 datetime_format = %d/%b/%Y:%H:%M:%S
               mode: '000400'
@@ -208,31 +198,17 @@ Resources:
                 curl https://s3.amazonaws.com//aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O
                 chmod +x ./awslogs-agent-setup.py
                 ./awslogs-agent-setup.py -n -r ${AWS::Region} -c /tmp/cwlogs/logs.conf
+                systemctl disable awslogs
               mode: '000400'
               owner: root
               group: root
           commands:
             run_cw_agent:
               command: '/bin/bash -xe /tmp/cwlogs/run.sh'
-  SpotFleetLogGroup:
+
+  InstanceLogGroup:
     Type: AWS::Logs::LogGroup
-    Properties:
-      RetentionInDays: 7
-  IAMFleetRole:
-    Type: AWS::IAM::Role
-    Properties:
-      AssumeRolePolicyDocument:
-        Version: '2012-10-17'
-        Statement:
-          - Effect: 'Allow'
-            Principal:
-              Service:
-                - 'spotfleet.amazonaws.com'
-            Action:
-              - 'sts:AssumeRole'
-      Path: '/'
-      ManagedPolicyArns:
-      - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole
+
   LogRole:
     Type: AWS::IAM::Role
     Properties:
@@ -259,7 +235,7 @@ Resources:
             Resource:
             - arn:aws:logs:*:*:*
             - arn:aws:s3:::*
-  LogRoleInstanceProfile:
+  InstanceProfile:
     Type: AWS::IAM::InstanceProfile
     Properties:
       Path: '/'
@@ -268,15 +244,18 @@ Resources:
 
   InstanceReadyWaitCondition:
     Type: AWS::CloudFormation::WaitCondition
+    DependsOn: SpotInstance
     CreationPolicy:
       ResourceSignal:
         Timeout: PT20M
+
   CreateAMI:
     Type: Custom::AMI
     DependsOn: InstanceReadyWaitCondition
     Properties:
       ServiceToken: !GetAtt CreateAMIFunction.Arn
-      SpotFleetRequestId: !Ref SpotFleet
+      InstanceId: !Ref SpotInstance
+      ImageName: !Ref ImageName
       IgnoreFunction: !Ref IgnoreCreateAMIFunction
   CreateAMIFunction:
     Type: AWS::Lambda::Function
@@ -285,12 +264,12 @@ Resources:
       Role: !GetAtt CreateAMILambdaExecutionRole.Arn
       Code:
         ZipFile: !Sub |
-          var AWS=require('aws-sdk');var response=require('cfn-response');exports.handler=function(event,context){console.log("Request received:\n",JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{}
-          console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
+          var aws=require('aws-sdk');var response=require('cfn-response');exports.handler=function(event,context){console.log("Request received:\n",JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{};console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
           function failed(err){console.log('FAILED:\n',err);return response.send(event,context,response.FAILED,err,physicalId)}
           if(event.ResourceProperties.IgnoreFunction=='true'){console.log('AMI not created (the function is ignored)');return success()}
-          var ec2=new AWS.EC2();if(event.RequestType=='Create'||event.RequestType=='Update'){var spotFleetRequestId=event.ResourceProperties.SpotFleetRequestId;if(!spotFleetRequestId){return failed('SpotFleetRequestId required')}
-          ec2.describeSpotFleetInstances({SpotFleetRequestId:spotFleetRequestId}).promise().then((data)=>{console.log("Spot Instances Response:\n",JSON.stringify(data));var instanceId=data.ActiveInstances[0].InstanceId;return ec2.createImage({InstanceId:instanceId,Name:event.RequestId}).promise()}).then((data)=>{console.log('Creating image:\n',JSON.stringify(data));physicalId=data.ImageId;return ec2.waitFor('imageAvailable',{ImageIds:[data.ImageId]}).promise()}).then((data)=>{console.log('Image available:\n',JSON.stringify(data));console.log('Cancelling Spot Request...');return ec2.cancelSpotFleetRequests({SpotFleetRequestIds:[spotFleetRequestId],TerminateInstances:!0}).promise()}).then((data)=>{console.log('Spot Request cancelled:\n',data);success()}).catch((err)=>failed(err))}else if(event.RequestType=='Delete'){if(!physicalId){console.log('AMI ID not specified')
+          var ec2=new aws.EC2({region:event.ResourceProperties.Region});if(event.RequestType=='Create'||event.RequestType=='Update'){var instanceId=event.ResourceProperties.InstanceId;if(!instanceId){return failed('InstanceId required')}
+          var imageName=event.ResourceProperties.ImageName;if(!imageName){return failed('ImageName required')}
+          ec2.createImage({InstanceId:instanceId,Name:imageName}).promise().then((data)=>{console.log('Creating image:\n',JSON.stringify(data));physicalId=data.ImageId;var tagsPromise=ec2.createTags({Resources:[data.ImageId],Tags:[{Key:'spotty:stack-id',Value:event.StackId}]}).promise();var imageAvailablePromise=ec2.waitFor('imageAvailable',{ImageIds:[data.ImageId]}).promise();return Promise.all([tagsPromise,imageAvailablePromise])}).then((data)=>{console.log('Image tagged:\n',JSON.stringify(data[0]));console.log('Image available:\n',JSON.stringify(data[1]));console.log('Terminating the instance...');return ec2.terminateInstances({InstanceIds:[instanceId]}).promise()}).then((data)=>{console.log('"terminateInstances" Response:\n',JSON.stringify(data));success()}).catch((err)=>failed(err))}else if(event.RequestType=='Delete'){if(!physicalId){console.log('AMI ID not specified')
           return success()}else if(physicalId.indexOf('ami-')!==0){console.log('Physical ID is not an AMI ID')
           return success()}
           console.log('Searching AMI with ID='+physicalId);ec2.describeImages({ImageIds:[physicalId]}).promise().then((data)=>{if(!data.Images.length){throw new Error('No images found')}
@@ -298,12 +277,6 @@ Resources:
           return ec2.deleteSnapshot({SnapshotId:data.Snapshots[0].SnapshotId}).promise()}).then((data)=>{console.log('Snapshot deleted:\n',data);success()}).catch((err)=>failed(err))}}
       Runtime: nodejs4.3
       Timeout: 300
-  CreateAMIFunctionLogGroup:
-    Type: AWS::Logs::LogGroup
-    DependsOn: CreateAMIFunction
-    Properties:
-      RetentionInDays: 7
-      LogGroupName: !Join ['', ['/aws/lambda/', !Ref CreateAMIFunction]]
   CreateAMILambdaExecutionRole:
     Type: AWS::IAM::Role
     Properties:
@@ -333,8 +306,8 @@ Resources:
               - 'ec2:DeregisterImage'
               - 'ec2:DescribeSnapshots'
               - 'ec2:DeleteSnapshot'
-              - 'ec2:DescribeSpotFleetInstances'
-              - 'ec2:CancelSpotFleetRequests'
+              - 'ec2:TerminateInstances'
+              - 'ec2:CreateTags'
               Resource: ['*']
 Outputs:
   BaseAMI:
@@ -343,6 +316,6 @@ Outputs:
   NewAMI:
     Description: Created AMI ID
     Value: !Ref CreateAMI
-  SpotFleetLogGroupName:
-    Description: The name of the CloudWatch log group
-    Value: !Ref SpotFleetLogGroup
+  InstanceLogGroupName:
+    Description: CloudWatch log group name for the instance
+    Value: !Ref InstanceLogGroup
